// NEXORA POS - Realistic Synthetic Enterprise Seed Data
import type {
  Product,
  Category,
  User,
  Location,
  Register,
  Supplier,
  Customer,
  Shift,
  CashMovement,
  InventoryMovement,
  PurchaseOrder,
  Sale,
} from './types';

export const INITIAL_LOCATIONS: Location[] = [
  {
    id: 'loc_flagship',
    name: 'Downtown Flagship',
    code: 'DF-01',
    address: '452 Market Street, Suite 100, San Francisco, CA',
    phone: '+1 (415) 890-4100',
    timezone: 'America/Los_Angeles',
    taxRate: 0.0875,
    currencySymbol: '$',
    currencyCode: 'USD',
  },
  {
    id: 'loc_express',
    name: 'Uptown Express Café',
    code: 'UE-02',
    address: '1280 4th Ave, San Francisco, CA',
    phone: '+1 (415) 890-4200',
    timezone: 'America/Los_Angeles',
    taxRate: 0.0875,
    currencySymbol: '$',
    currencyCode: 'USD',
  },
];

export const INITIAL_REGISTERS: Register[] = [
  {
    id: 'reg_01',
    locationId: 'loc_flagship',
    name: 'Counter 1 (Main Touch POS)',
    code: 'POS-01',
    isOnline: true,
  },
  {
    id: 'reg_02',
    locationId: 'loc_flagship',
    name: 'Counter 2 (Express Tablet)',
    code: 'POS-02',
    isOnline: true,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_owner',
    name: 'Elena Vance',
    email: 'elena@nexora.io',
    role: 'OWNER',
    pin: '1234',
    permissions: [
      'sales.create',
      'sales.void',
      'sales.refund',
      'sales.discount.apply',
      'sales.discount.override',
      'inventory.read',
      'inventory.adjust',
      'inventory.transfer',
      'purchases.create',
      'purchases.receive',
      'cash.open_shift',
      'cash.close_shift',
      'cash.adjust',
      'reports.sales.read',
      'reports.finance.read',
      'users.manage',
      'settings.manage',
    ],
  },
  {
    id: 'usr_manager',
    name: 'Marcus Cole',
    email: 'marcus@nexora.io',
    role: 'MANAGER',
    pin: '2233',
    permissions: [
      'sales.create',
      'sales.void',
      'sales.refund',
      'sales.discount.apply',
      'sales.discount.override',
      'inventory.read',
      'inventory.adjust',
      'inventory.transfer',
      'purchases.create',
      'purchases.receive',
      'cash.open_shift',
      'cash.close_shift',
      'cash.adjust',
      'reports.sales.read',
    ],
  },
  {
    id: 'usr_cashier',
    name: 'Sarah Chen',
    email: 'sarah@nexora.io',
    role: 'CASHIER',
    pin: '1111',
    permissions: [
      'sales.create',
      'sales.discount.apply',
      'cash.open_shift',
      'cash.close_shift',
    ],
  },
  {
    id: 'usr_kitchen',
    name: 'Dante Diaz',
    email: 'dante@nexora.io',
    role: 'KITCHEN',
    pin: '5555',
    permissions: ['kds.manage'],
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat_coffee', name: 'Coffee & Espresso', code: 'COFFEE', color: '#78350f', mode: 'CAFE' },
  { id: 'cat_tea', name: 'Artisan Teas', code: 'TEA', color: '#065f46', mode: 'CAFE' },
  { id: 'cat_pastry', name: 'Bakery & Pastry', code: 'PASTRY', color: '#92400e', mode: 'CAFE' },
  { id: 'cat_toast', name: 'Warm Brunch & Bowls', code: 'FOOD', color: '#b45309', mode: 'CAFE' },
  { id: 'cat_beverage', name: 'Bottled Drinks', code: 'BEV', color: '#0284c7', mode: 'RETAIL' },
  { id: 'cat_snacks', name: 'Gourmet Snacks', code: 'SNACK', color: '#ea580c', mode: 'RETAIL' },
  { id: 'cat_retail_beans', name: 'Packaged Beans', code: 'BEANS', color: '#475569', mode: 'ALL' },
  { id: 'cat_merch', name: 'Merchandise & Cups', code: 'MERCH', color: '#6b21a8', mode: 'RETAIL' },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Cafe Items with Modifiers
  {
    id: 'prod_flat_white',
    name: 'Artisan Flat White (Double)',
    sku: 'BEV-FW-01',
    barcode: '890100101',
    categoryId: 'cat_coffee',
    brand: 'Nexora Roastery',
    unit: 'cup',
    purchaseCost: 0.95,
    sellingPrice: 4.85,
    taxRate: 0.0875,
    stockQuantity: 120,
    minStockLevel: 25,
    active: true,
    type: 'RECIPE',
    preparationStation: 'BAR',
    image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=600&auto=format&fit=crop&q=80',
    modifierGroups: [
      {
        id: 'mod_milk',
        name: 'Milk Preference',
        required: true,
        options: [
          { id: 'opt_whole', name: 'Whole Organic Milk', priceDelta: 0 },
          { id: 'opt_oat', name: 'Oat Milk (Barista Edition)', priceDelta: 0.85 },
          { id: 'opt_almond', name: 'Almond Milk', priceDelta: 0.85 },
        ],
      },
      {
        id: 'mod_shots',
        name: 'Espresso Strength',
        required: false,
        options: [
          { id: 'opt_extra_shot', name: 'Add Extra Ristretto Shot', priceDelta: 1.0 },
          { id: 'opt_decaf', name: 'Swiss Water Decaf', priceDelta: 0.5 },
        ],
      },
    ],
    description: 'Velvety micro-foam poured over a double ristretto shot of our Single Origin Ethiopian bean.',
  },
  {
    id: 'prod_cold_brew',
    name: 'Nitro Cold Brew (16oz)',
    sku: 'BEV-NCB-02',
    barcode: '890100102',
    categoryId: 'cat_coffee',
    brand: 'Nexora Roastery',
    unit: 'cup',
    purchaseCost: 0.8,
    sellingPrice: 5.5,
    taxRate: 0.0875,
    stockQuantity: 65,
    minStockLevel: 15,
    active: true,
    type: 'RECIPE',
    preparationStation: 'BAR',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80',
    modifierGroups: [
      {
        id: 'mod_syrup',
        name: 'House Syrups',
        required: false,
        options: [
          { id: 'opt_vanilla', name: 'Madagascar Vanilla (Housemade)', priceDelta: 0.75 },
          { id: 'opt_caramel', name: 'Salted Caramel Drizzle', priceDelta: 0.75 },
        ],
      },
    ],
    description: '18-hour cold steeped single origin coffee infused with nitrogen for an ultra-creamy head.',
  },
  {
    id: 'prod_matcha_latte',
    name: 'Kyoto Ceremonial Matcha Latte',
    sku: 'BEV-MTC-03',
    barcode: '890100103',
    categoryId: 'cat_tea',
    brand: 'Uji Direct',
    unit: 'cup',
    purchaseCost: 1.4,
    sellingPrice: 6.25,
    taxRate: 0.0875,
    stockQuantity: 42,
    minStockLevel: 10,
    active: true,
    type: 'RECIPE',
    preparationStation: 'BAR',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&auto=format&fit=crop&q=80',
    modifierGroups: [
      {
        id: 'mod_sweetness',
        name: 'Sweetness',
        required: true,
        options: [
          { id: 'opt_unsweet', name: 'Unsweetened (Pure Matcha)', priceDelta: 0 },
          { id: 'opt_agave', name: 'Raw Organic Agave', priceDelta: 0.5 },
        ],
      },
    ],
    description: 'First harvest stone-ground ceremonial grade matcha whisked with warm textured milk.',
  },
  {
    id: 'prod_croissant',
    name: 'French Butter Croissant',
    sku: 'BAK-CRS-01',
    barcode: '890100201',
    categoryId: 'cat_pastry',
    brand: 'La Boulange',
    unit: 'piece',
    purchaseCost: 1.2,
    sellingPrice: 3.95,
    taxRate: 0.0875,
    stockQuantity: 18,
    minStockLevel: 8,
    active: true,
    type: 'STANDARD',
    preparationStation: 'KITCHEN',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
    description: '27-layer laminated AOP butter pastry, baked golden fresh every morning.',
  },
  {
    id: 'prod_almond_croissant',
    name: 'Double Baked Almond Croissant',
    sku: 'BAK-ALM-02',
    barcode: '890100202',
    categoryId: 'cat_pastry',
    brand: 'La Boulange',
    unit: 'piece',
    purchaseCost: 1.6,
    sellingPrice: 4.75,
    taxRate: 0.0875,
    stockQuantity: 12,
    minStockLevel: 6,
    active: true,
    type: 'STANDARD',
    preparationStation: 'KITCHEN',
    image: 'https://images.unsplash.com/photo-1623334044303-241021148842?w=600&auto=format&fit=crop&q=80',
    description: 'Filled with rich almond frangipane cream and topped with toasted sliced almonds.',
  },
  {
    id: 'prod_avocado_toast',
    name: 'Sourdough Smashed Avocado Toast',
    sku: 'FOOD-AVO-01',
    barcode: '890100301',
    categoryId: 'cat_toast',
    brand: 'Nexora Kitchen',
    unit: 'plate',
    purchaseCost: 2.8,
    sellingPrice: 11.5,
    taxRate: 0.0875,
    stockQuantity: 34,
    minStockLevel: 10,
    active: true,
    type: 'RECIPE',
    preparationStation: 'KITCHEN',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80',
    modifierGroups: [
      {
        id: 'mod_toast_addon',
        name: 'Add-Ons',
        required: false,
        options: [
          { id: 'opt_egg', name: 'Soft Poached Organic Egg', priceDelta: 2.0 },
          { id: 'opt_salmon', name: 'House Smoked Salmon', priceDelta: 4.5 },
          { id: 'opt_feta', name: 'Crumbled Goat Feta', priceDelta: 1.5 },
        ],
      },
    ],
    description: 'Seeded sourdough with Hass avocado mash, pickled shallots, microgreens, and chili flakes.',
  },

  // Retail Packaged Products
  {
    id: 'prod_beans_ethiopia',
    name: 'Guji Highland Whole Bean Coffee (12oz)',
    sku: 'RET-BN-ETH',
    barcode: '890100401',
    categoryId: 'cat_retail_beans',
    brand: 'Nexora Roastery',
    unit: 'bag',
    purchaseCost: 7.5,
    sellingPrice: 18.0,
    taxRate: 0.0,
    stockQuantity: 45,
    minStockLevel: 12,
    active: true,
    type: 'STANDARD',
    preparationStation: 'NONE',
    image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=600&auto=format&fit=crop&q=80',
    description: 'Light roast with notes of jasmine, bergamot peach, and wild blossom honey.',
  },
  {
    id: 'prod_beans_colombia',
    name: 'Huila Supremo Single Origin (12oz)',
    sku: 'RET-BN-COL',
    barcode: '890100402',
    categoryId: 'cat_retail_beans',
    brand: 'Nexora Roastery',
    unit: 'bag',
    purchaseCost: 6.8,
    sellingPrice: 16.5,
    taxRate: 0.0,
    stockQuantity: 58,
    minStockLevel: 15,
    active: true,
    type: 'STANDARD',
    preparationStation: 'NONE',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    description: 'Medium roast with decadent brown sugar, dark cocoa, and red cherry notes.',
  },
  {
    id: 'prod_sparkling_water',
    name: 'Mountain Spring Sparkling Mineral (500ml)',
    sku: 'RET-SPK-01',
    barcode: '890100501',
    categoryId: 'cat_beverage',
    brand: 'Alpine Pure',
    unit: 'bottle',
    purchaseCost: 0.85,
    sellingPrice: 2.75,
    taxRate: 0.0875,
    stockQuantity: 84,
    minStockLevel: 24,
    active: true,
    type: 'STANDARD',
    preparationStation: 'NONE',
    image: 'https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=600&auto=format&fit=crop&q=80',
    description: 'Crisp, refreshing naturally carbonated mountain spring mineral water.',
  },
  {
    id: 'prod_organic_kombucha',
    name: 'Ginger Lemon Probiotic Kombucha (16oz)',
    sku: 'RET-KMB-02',
    barcode: '890100502',
    categoryId: 'cat_beverage',
    brand: 'Wild Ferment Co.',
    unit: 'bottle',
    purchaseCost: 1.9,
    sellingPrice: 4.95,
    taxRate: 0.0875,
    stockQuantity: 36,
    minStockLevel: 12,
    active: true,
    type: 'STANDARD',
    preparationStation: 'NONE',
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&auto=format&fit=crop&q=80',
    description: 'Raw cold-pressed ginger root blended with organic green tea kombucha.',
  },
  {
    id: 'prod_truffle_crisps',
    name: 'Black Truffle & Olive Oil Crisps (150g)',
    sku: 'RET-TRF-01',
    barcode: '890100601',
    categoryId: 'cat_snacks',
    brand: 'Torres Select',
    unit: 'bag',
    purchaseCost: 2.4,
    sellingPrice: 5.5,
    taxRate: 0.0875,
    stockQuantity: 28,
    minStockLevel: 10,
    active: true,
    type: 'STANDARD',
    preparationStation: 'NONE',
    image: 'https://images.unsplash.com/photo-1517093709121-6a166a5c267a?w=600&auto=format&fit=crop&q=80',
    description: 'Artisanal hand-cooked Spanish potato chips flavored with genuine black summer truffle.',
  },
  {
    id: 'prod_tumbler',
    name: 'Ceramic Core Insulated Tumbler (16oz)',
    sku: 'RET-TMB-01',
    barcode: '890100701',
    categoryId: 'cat_merch',
    brand: 'Nexora Gear',
    unit: 'piece',
    purchaseCost: 14.0,
    sellingPrice: 32.0,
    taxRate: 0.0875,
    stockQuantity: 19,
    minStockLevel: 5,
    active: true,
    type: 'STANDARD',
    preparationStation: 'NONE',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    description: 'Double-walled stainless steel thermal mug with ceramic inner coating for pure taste.',
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup_roasters',
    name: 'Apex Green Bean Importers',
    contactPerson: 'David Miller',
    email: 'orders@apexgreens.com',
    phone: '+1 (510) 444-1290',
    address: '800 7th St, Oakland, CA',
    productsSuppliedCount: 6,
  },
  {
    id: 'sup_bakery',
    name: 'La Boulange Artisan Bakery',
    contactPerson: 'Claire Dubois',
    email: 'deliveries@laboulange.sf',
    phone: '+1 (415) 321-9988',
    address: '1440 Pine St, San Francisco, CA',
    productsSuppliedCount: 4,
  },
  {
    id: 'sup_packaging',
    name: 'EcoPack Sustainable Goods',
    contactPerson: 'Kenji Sato',
    email: 'support@ecopack.co',
    phone: '+1 (408) 555-8911',
    address: '220 Innovation Way, San Jose, CA',
    productsSuppliedCount: 8,
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_01',
    name: 'Alexander Wright',
    phone: '+1 (415) 555-0192',
    email: 'alex.wright@gmail.com',
    points: 340,
    totalSpent: 482.5,
    visitCount: 28,
    tier: 'GOLD',
    notes: 'Likes extra hot flat white with oat milk.',
    createdAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'cust_02',
    name: 'Maya Lin',
    phone: '+1 (415) 555-0381',
    email: 'maya.lin@outlook.com',
    points: 120,
    totalSpent: 165.0,
    visitCount: 12,
    tier: 'SILVER',
    notes: 'Usually buys Guji whole bean coffee.',
    createdAt: '2026-08-22T14:30:00Z',
  },
  {
    id: 'cust_03',
    name: 'Jonathan Rivera',
    phone: '+1 (415) 555-0774',
    email: 'jrivera@techcorp.io',
    points: 760,
    totalSpent: 1140.0,
    visitCount: 64,
    tier: 'VIP',
    notes: 'Corporate account counter purchases.',
    createdAt: '2026-07-01T09:15:00Z',
  },
];

export const INITIAL_SHIFT: Shift = {
  id: 'shift_active_01',
  organizationId: 'org_nexora',
  locationId: 'loc_flagship',
  registerId: 'reg_01',
  cashierId: 'usr_cashier',
  cashierName: 'Sarah Chen',
  openedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  closedAt: null,
  openingFloat: 200.0,
  status: 'OPEN',
  cashSales: 185.5,
  cardSales: 432.0,
  mobileSales: 96.5,
  cashRefunds: 0.0,
  cashIn: 0.0,
  cashOut: 25.0,
  safeDrops: 0.0,
  expectedCash: 360.5, // 200 float + 185.5 cash sales - 25 cash out
  countedCash: null,
  variance: null,
  varianceReason: null,
  notes: 'Morning rush shift. Opened on time.',
};

export const INITIAL_INVENTORY_MOVEMENTS: InventoryMovement[] = [
  {
    id: 'mov_init_01',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    productId: 'prod_beans_ethiopia',
    productName: 'Guji Highland Whole Bean Coffee (12oz)',
    movementType: 'OPENING',
    quantity: 50,
    unitCost: 7.5,
    referenceType: 'MANUAL',
    reasonCode: 'Initial store inventory opening count',
    createdBy: 'Elena Vance',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'mov_init_02',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    productId: 'prod_beans_ethiopia',
    productName: 'Guji Highland Whole Bean Coffee (12oz)',
    movementType: 'SALE',
    quantity: -5,
    unitCost: 7.5,
    referenceType: 'SALE',
    referenceId: 'NX-1002',
    reasonCode: 'Point of sale completed',
    createdBy: 'Sarah Chen',
    createdAt: '2026-09-18T11:24:00Z',
  },
  {
    id: 'mov_init_03',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    productId: 'prod_tumbler',
    productName: 'Ceramic Core Insulated Tumbler (16oz)',
    movementType: 'OPENING',
    quantity: 20,
    unitCost: 14.0,
    referenceType: 'MANUAL',
    reasonCode: 'Opening balance',
    createdBy: 'Marcus Cole',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'mov_init_04',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    productId: 'prod_tumbler',
    productName: 'Ceramic Core Insulated Tumbler (16oz)',
    movementType: 'SALE',
    quantity: -1,
    unitCost: 14.0,
    referenceType: 'SALE',
    referenceId: 'NX-1008',
    reasonCode: 'Customer purchase',
    createdBy: 'Sarah Chen',
    createdAt: '2026-09-19T09:15:00Z',
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po_01',
    poNumber: 'PO-2026-089',
    supplierId: 'sup_roasters',
    supplierName: 'Apex Green Bean Importers',
    locationId: 'loc_flagship',
    status: 'ORDERED',
    items: [
      {
        productId: 'prod_beans_ethiopia',
        productName: 'Guji Highland Whole Bean Coffee (12oz)',
        sku: 'RET-BN-ETH',
        quantity: 30,
        unitCost: 7.5,
        receivedQuantity: 0,
      },
      {
        productId: 'prod_beans_colombia',
        productName: 'Huila Supremo Single Origin (12oz)',
        sku: 'RET-BN-COL',
        quantity: 40,
        unitCost: 6.8,
        receivedQuantity: 0,
      },
    ],
    totalCost: 497.0,
    orderedAt: '2026-09-17T15:30:00Z',
    notes: 'Restock expected by Wednesday delivery window.',
  },
];

export const INITIAL_CASH_MOVEMENTS: CashMovement[] = [
  {
    id: 'cmov_01',
    shiftId: 'shift_active_01',
    type: 'CASH_OUT',
    amount: 25.0,
    reason: 'Bought whole milk from local dairy',
    cashierId: 'usr_cashier',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale_hist_01',
    orderNumber: 'NX-1001',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    customerId: 'cust_01',
    customerName: 'Alexander Wright',
    items: [
      {
        cartItemId: 'item_h01_1',
        productId: 'prod_flat_white',
        name: 'Artisan Flat White (Double)',
        sku: 'BEV-FW-01',
        unitPrice: 4.85,
        purchaseCost: 0.95,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.85,
        total: 10.55,
      },
      {
        cartItemId: 'item_h01_2',
        productId: 'prod_croissant',
        name: 'French Butter Croissant',
        sku: 'BAK-CRS-01',
        unitPrice: 3.95,
        purchaseCost: 1.2,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.69,
        total: 8.59,
      },
    ],
    subtotal: 17.6,
    discountTotal: 0,
    taxTotal: 1.54,
    total: 19.14,
    payments: [{ id: 'pay_h01', method: 'CARD', amount: 19.14, status: 'CAPTURED', processedAt: '2026-09-06T09:12:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-06T09:12:05Z',
    createdAt: '2026-09-06T09:12:00Z',
  },
  {
    id: 'sale_hist_02',
    orderNumber: 'NX-1002',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    customerId: 'cust_02',
    customerName: 'Maya Lin',
    items: [
      {
        cartItemId: 'item_h02_1',
        productId: 'prod_beans_ethiopia',
        name: 'Guji Highland Whole Bean Coffee (12oz)',
        sku: 'RET-BN-ETH',
        unitPrice: 18.0,
        purchaseCost: 7.5,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0,
        total: 36.0,
      },
      {
        cartItemId: 'item_h02_2',
        productId: 'prod_tumbler',
        name: 'Ceramic Core Insulated Tumbler (16oz)',
        sku: 'RET-TMB-01',
        unitPrice: 32.0,
        purchaseCost: 14.0,
        quantity: 1,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 2.8,
        total: 34.8,
      },
    ],
    subtotal: 50.0,
    discountTotal: 0,
    taxTotal: 2.8,
    total: 52.8,
    payments: [{ id: 'pay_h02', method: 'CARD', amount: 52.8, status: 'CAPTURED', processedAt: '2026-09-07T14:45:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-07T14:45:05Z',
    createdAt: '2026-09-07T14:45:00Z',
  },
  {
    id: 'sale_hist_03',
    orderNumber: 'NX-1003',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h03_1',
        productId: 'prod_almond_croissant',
        name: 'Double Baked Almond Croissant',
        sku: 'BAK-ALM-02',
        unitPrice: 4.75,
        purchaseCost: 1.6,
        quantity: 3,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 1.25,
        total: 15.5,
      },
      {
        cartItemId: 'item_h03_2',
        productId: 'prod_cold_brew',
        name: 'Nitro Cold Brew (16oz)',
        sku: 'BEV-NCB-02',
        unitPrice: 5.5,
        purchaseCost: 0.8,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.96,
        total: 11.96,
      },
    ],
    subtotal: 25.25,
    discountTotal: 0,
    taxTotal: 2.21,
    total: 27.46,
    payments: [{ id: 'pay_h03', method: 'MOBILE_WALLET', amount: 27.46, status: 'CAPTURED', processedAt: '2026-09-08T10:30:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-08T10:30:05Z',
    createdAt: '2026-09-08T10:30:00Z',
  },
  {
    id: 'sale_hist_04',
    orderNumber: 'NX-1004',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h04_1',
        productId: 'prod_avocado_toast',
        name: 'Sourdough Smashed Avocado Toast',
        sku: 'FOOD-AVO-01',
        unitPrice: 11.5,
        purchaseCost: 2.8,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 2.01,
        total: 25.01,
      },
      {
        cartItemId: 'item_h04_2',
        productId: 'prod_flat_white',
        name: 'Artisan Flat White (Double)',
        sku: 'BEV-FW-01',
        unitPrice: 4.85,
        purchaseCost: 0.95,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.85,
        total: 10.55,
      },
      {
        cartItemId: 'item_h04_3',
        productId: 'prod_croissant',
        name: 'French Butter Croissant',
        sku: 'BAK-CRS-01',
        unitPrice: 3.95,
        purchaseCost: 1.2,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.69,
        total: 8.59,
      },
    ],
    subtotal: 36.7,
    discountTotal: 0,
    taxTotal: 3.55,
    total: 40.25,
    payments: [{ id: 'pay_h04', method: 'CARD', amount: 40.25, status: 'CAPTURED', processedAt: '2026-09-09T12:15:00Z' }],
    status: 'COMPLETED',
    orderType: 'DINE_IN',
    isOfflineCreated: false,
    syncedAt: '2026-09-09T12:15:05Z',
    createdAt: '2026-09-09T12:15:00Z',
  },
  {
    id: 'sale_hist_05',
    orderNumber: 'NX-1005',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h05_1',
        productId: 'prod_truffle_crisps',
        name: 'Black Truffle & Olive Oil Crisps (150g)',
        sku: 'RET-TRF-01',
        unitPrice: 5.5,
        purchaseCost: 2.4,
        quantity: 3,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 1.44,
        total: 17.94,
      },
      {
        cartItemId: 'item_h05_2',
        productId: 'prod_sparkling_water',
        name: 'Mountain Spring Sparkling Mineral (500ml)',
        sku: 'RET-SPK-01',
        unitPrice: 2.75,
        purchaseCost: 0.85,
        quantity: 4,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.96,
        total: 11.96,
      },
    ],
    subtotal: 27.5,
    discountTotal: 0,
    taxTotal: 2.4,
    total: 29.9,
    payments: [{ id: 'pay_h05', method: 'CASH', amount: 30.0, status: 'CAPTURED', processedAt: '2026-09-10T15:10:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-10T15:10:05Z',
    createdAt: '2026-09-10T15:10:00Z',
  },
  {
    id: 'sale_hist_06',
    orderNumber: 'NX-1006',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h06_1',
        productId: 'prod_beans_colombia',
        name: 'Huila Supremo Single Origin (12oz)',
        sku: 'RET-BN-COL',
        unitPrice: 16.5,
        purchaseCost: 6.8,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0,
        total: 33.0,
      },
      {
        cartItemId: 'item_h06_2',
        productId: 'prod_almond_croissant',
        name: 'Double Baked Almond Croissant',
        sku: 'BAK-ALM-02',
        unitPrice: 4.75,
        purchaseCost: 1.6,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.83,
        total: 10.33,
      },
    ],
    subtotal: 42.5,
    discountTotal: 0,
    taxTotal: 0.83,
    total: 43.33,
    payments: [{ id: 'pay_h06', method: 'CARD', amount: 43.33, status: 'CAPTURED', processedAt: '2026-09-11T11:00:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-11T11:00:05Z',
    createdAt: '2026-09-11T11:00:00Z',
  },
  {
    id: 'sale_hist_07',
    orderNumber: 'NX-1007',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h07_1',
        productId: 'prod_matcha_latte',
        name: 'Kyoto Ceremonial Matcha Latte',
        sku: 'BEV-MTC-03',
        unitPrice: 6.25,
        purchaseCost: 1.4,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 1.09,
        total: 13.59,
      },
      {
        cartItemId: 'item_h07_2',
        productId: 'prod_organic_kombucha',
        name: 'Ginger Lemon Probiotic Kombucha (16oz)',
        sku: 'RET-KMB-02',
        unitPrice: 4.95,
        purchaseCost: 1.9,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.87,
        total: 10.77,
      },
      {
        cartItemId: 'item_h07_3',
        productId: 'prod_croissant',
        name: 'French Butter Croissant',
        sku: 'BAK-CRS-01',
        unitPrice: 3.95,
        purchaseCost: 1.2,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.69,
        total: 8.59,
      },
    ],
    subtotal: 30.3,
    discountTotal: 0,
    taxTotal: 2.65,
    total: 32.95,
    payments: [{ id: 'pay_h07', method: 'CARD', amount: 32.95, status: 'CAPTURED', processedAt: '2026-09-12T13:40:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-12T13:40:05Z',
    createdAt: '2026-09-12T13:40:00Z',
  },
  {
    id: 'sale_hist_08',
    orderNumber: 'NX-1008',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h08_1',
        productId: 'prod_flat_white',
        name: 'Artisan Flat White (Double)',
        sku: 'BEV-FW-01',
        unitPrice: 4.85,
        purchaseCost: 0.95,
        quantity: 4,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 1.7,
        total: 21.1,
      },
      {
        cartItemId: 'item_h08_2',
        productId: 'prod_almond_croissant',
        name: 'Double Baked Almond Croissant',
        sku: 'BAK-ALM-02',
        unitPrice: 4.75,
        purchaseCost: 1.6,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.83,
        total: 10.33,
      },
    ],
    subtotal: 28.9,
    discountTotal: 0,
    taxTotal: 2.53,
    total: 31.43,
    payments: [{ id: 'pay_h08', method: 'CARD', amount: 31.43, status: 'CAPTURED', processedAt: '2026-09-13T09:20:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-13T09:20:05Z',
    createdAt: '2026-09-13T09:20:00Z',
  },
  {
    id: 'sale_hist_09',
    orderNumber: 'NX-1009',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h09_1',
        productId: 'prod_beans_ethiopia',
        name: 'Guji Highland Whole Bean Coffee (12oz)',
        sku: 'RET-BN-ETH',
        unitPrice: 18.0,
        purchaseCost: 7.5,
        quantity: 3,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0,
        total: 54.0,
      },
      {
        cartItemId: 'item_h09_2',
        productId: 'prod_cold_brew',
        name: 'Nitro Cold Brew (16oz)',
        sku: 'BEV-NCB-02',
        unitPrice: 5.5,
        purchaseCost: 0.8,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.96,
        total: 11.96,
      },
    ],
    subtotal: 65.0,
    discountTotal: 0,
    taxTotal: 0.96,
    total: 65.96,
    payments: [{ id: 'pay_h09', method: 'CARD', amount: 65.96, status: 'CAPTURED', processedAt: '2026-09-14T16:05:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-14T16:05:05Z',
    createdAt: '2026-09-14T16:05:00Z',
  },
  {
    id: 'sale_hist_10',
    orderNumber: 'NX-1010',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h10_1',
        productId: 'prod_croissant',
        name: 'French Butter Croissant',
        sku: 'BAK-CRS-01',
        unitPrice: 3.95,
        purchaseCost: 1.2,
        quantity: 3,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 1.04,
        total: 12.89,
      },
      {
        cartItemId: 'item_h10_2',
        productId: 'prod_almond_croissant',
        name: 'Double Baked Almond Croissant',
        sku: 'BAK-ALM-02',
        unitPrice: 4.75,
        purchaseCost: 1.6,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.83,
        total: 10.33,
      },
      {
        cartItemId: 'item_h10_3',
        productId: 'prod_truffle_crisps',
        name: 'Black Truffle & Olive Oil Crisps (150g)',
        sku: 'RET-TRF-01',
        unitPrice: 5.5,
        purchaseCost: 2.4,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.96,
        total: 11.96,
      },
    ],
    subtotal: 32.35,
    discountTotal: 0,
    taxTotal: 2.83,
    total: 35.18,
    payments: [{ id: 'pay_h10', method: 'CARD', amount: 35.18, status: 'CAPTURED', processedAt: '2026-09-15T10:45:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-15T10:45:05Z',
    createdAt: '2026-09-15T10:45:00Z',
  },
  {
    id: 'sale_hist_11',
    orderNumber: 'NX-1011',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h11_1',
        productId: 'prod_avocado_toast',
        name: 'Sourdough Smashed Avocado Toast',
        sku: 'FOOD-AVO-01',
        unitPrice: 11.5,
        purchaseCost: 2.8,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 2.01,
        total: 25.01,
      },
      {
        cartItemId: 'item_h11_2',
        productId: 'prod_sparkling_water',
        name: 'Mountain Spring Sparkling Mineral (500ml)',
        sku: 'RET-SPK-01',
        unitPrice: 2.75,
        purchaseCost: 0.85,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.48,
        total: 5.98,
      },
    ],
    subtotal: 28.5,
    discountTotal: 0,
    taxTotal: 2.49,
    total: 30.99,
    payments: [{ id: 'pay_h11', method: 'MOBILE_WALLET', amount: 30.99, status: 'CAPTURED', processedAt: '2026-09-16T12:30:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-16T12:30:05Z',
    createdAt: '2026-09-16T12:30:00Z',
  },
  {
    id: 'sale_hist_12',
    orderNumber: 'NX-1012',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h12_1',
        productId: 'prod_flat_white',
        name: 'Artisan Flat White (Double)',
        sku: 'BEV-FW-01',
        unitPrice: 4.85,
        purchaseCost: 0.95,
        quantity: 3,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 1.27,
        total: 15.82,
      },
      {
        cartItemId: 'item_h12_2',
        productId: 'prod_croissant',
        name: 'French Butter Croissant',
        sku: 'BAK-CRS-01',
        unitPrice: 3.95,
        purchaseCost: 1.2,
        quantity: 3,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 1.04,
        total: 12.89,
      },
      {
        cartItemId: 'item_h12_3',
        productId: 'prod_almond_croissant',
        name: 'Double Baked Almond Croissant',
        sku: 'BAK-ALM-02',
        unitPrice: 4.75,
        purchaseCost: 1.6,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.83,
        total: 10.33,
      },
    ],
    subtotal: 35.9,
    discountTotal: 0,
    taxTotal: 3.14,
    total: 39.04,
    payments: [{ id: 'pay_h12', method: 'CARD', amount: 39.04, status: 'CAPTURED', processedAt: '2026-09-17T08:50:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-17T08:50:05Z',
    createdAt: '2026-09-17T08:50:00Z',
  },
  {
    id: 'sale_hist_13',
    orderNumber: 'NX-1013',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h13_1',
        productId: 'prod_beans_colombia',
        name: 'Huila Supremo Single Origin (12oz)',
        sku: 'RET-BN-COL',
        unitPrice: 16.5,
        purchaseCost: 6.8,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0,
        total: 33.0,
      },
      {
        cartItemId: 'item_h13_2',
        productId: 'prod_cold_brew',
        name: 'Nitro Cold Brew (16oz)',
        sku: 'BEV-NCB-02',
        unitPrice: 5.5,
        purchaseCost: 0.8,
        quantity: 3,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 1.44,
        total: 17.94,
      },
    ],
    subtotal: 49.5,
    discountTotal: 0,
    taxTotal: 1.44,
    total: 50.94,
    payments: [{ id: 'pay_h13', method: 'CARD', amount: 50.94, status: 'CAPTURED', processedAt: '2026-09-18T14:15:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-18T14:15:05Z',
    createdAt: '2026-09-18T14:15:00Z',
  },
  {
    id: 'sale_hist_14',
    orderNumber: 'NX-1014',
    organizationId: 'org_nexora',
    locationId: 'loc_flagship',
    registerId: 'reg_01',
    cashierId: 'usr_cashier',
    cashierName: 'Sarah Chen',
    items: [
      {
        cartItemId: 'item_h14_1',
        productId: 'prod_flat_white',
        name: 'Artisan Flat White (Double)',
        sku: 'BEV-FW-01',
        unitPrice: 4.85,
        purchaseCost: 0.95,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.85,
        total: 10.55,
      },
      {
        cartItemId: 'item_h14_2',
        productId: 'prod_croissant',
        name: 'French Butter Croissant',
        sku: 'BAK-CRS-01',
        unitPrice: 3.95,
        purchaseCost: 1.2,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.69,
        total: 8.59,
      },
      {
        cartItemId: 'item_h14_3',
        productId: 'prod_truffle_crisps',
        name: 'Black Truffle & Olive Oil Crisps (150g)',
        sku: 'RET-TRF-01',
        unitPrice: 5.5,
        purchaseCost: 2.4,
        quantity: 2,
        discountPercentage: 0,
        discountAmount: 0,
        taxAmount: 0.96,
        total: 11.96,
      },
    ],
    subtotal: 28.6,
    discountTotal: 0,
    taxTotal: 2.5,
    total: 31.1,
    payments: [{ id: 'pay_h14', method: 'CARD', amount: 31.1, status: 'CAPTURED', processedAt: '2026-09-19T10:05:00Z' }],
    status: 'COMPLETED',
    orderType: 'COUNTER',
    isOfflineCreated: false,
    syncedAt: '2026-09-19T10:05:05Z',
    createdAt: '2026-09-19T10:05:00Z',
  },
];

import { db } from './db';

export async function seedDatabase(): Promise<void> {
  await db.transaction(
    'rw',
    [
      db.locations,
      db.registers,
      db.users,
      db.categories,
      db.products,
      db.customers,
      db.suppliers,
      db.shifts,
      db.cashMovements,
      db.inventoryMovements,
      db.purchaseOrders,
      db.heldOrders,
      db.sales,
      db.syncOutbox,
    ],
    async () => {
      // Clear tables
      await Promise.all([
        db.locations.clear(),
        db.registers.clear(),
        db.users.clear(),
        db.categories.clear(),
        db.products.clear(),
        db.customers.clear(),
        db.suppliers.clear(),
        db.shifts.clear(),
        db.cashMovements.clear(),
        db.inventoryMovements.clear(),
        db.purchaseOrders.clear(),
        db.heldOrders.clear(),
        db.sales.clear(),
        db.syncOutbox.clear(),
      ]);

      // Bulk add seed records
      await db.locations.bulkAdd(INITIAL_LOCATIONS);
      await db.registers.bulkAdd(INITIAL_REGISTERS);
      await db.users.bulkAdd(INITIAL_USERS);
      await db.categories.bulkAdd(INITIAL_CATEGORIES);
      await db.products.bulkAdd(INITIAL_PRODUCTS);
      await db.customers.bulkAdd(INITIAL_CUSTOMERS);
      await db.suppliers.bulkAdd(INITIAL_SUPPLIERS);
      await db.shifts.bulkAdd([INITIAL_SHIFT]);
      await db.cashMovements.bulkAdd(INITIAL_CASH_MOVEMENTS);
      await db.inventoryMovements.bulkAdd(INITIAL_INVENTORY_MOVEMENTS);
      await db.purchaseOrders.bulkAdd(INITIAL_PURCHASE_ORDERS);
      await db.sales.bulkAdd(INITIAL_SALES);
    }
  );
}


